apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-v3aw
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/jhutar-tenant/my-app/devfile-sample-v3aw@sha256:eb9386e7b563f4b28946909bef22f5b741cbd95b70edb7d604f250e7cdef06d6
        name: my-nodejs
        resources: {}
status: {}
